# Generated by Django 4.1.6 on 2023-02-11 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeraddress',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='customerpayment',
            options={'ordering': ('-created_at',)},
        ),
    ]
