# Generated by Django 4.1.6 on 2023-02-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_customer_groups_customer_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='address_line1',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='address_line2',
            field=models.CharField(blank=True, default='None', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='country',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='postal_code',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='telephone',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
    ]
