# Generated by Django 4.1.6 on 2023-02-06 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_customeraddress_address_line1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('Cash', 'Cash'), ('Mobile Payment', 'Mobile Payment'), ('Credit Card', 'Credit Card')], default='Mobile Payment', max_length=15)),
                ('provider', models.CharField(choices=[('Stripe', 'Stripe'), ('PayPal', 'PayPal'), ('M-Pesa', 'M-Pesa')], default='Stripe', max_length=6)),
                ('account_no', models.CharField(max_length=100)),
                ('expiry', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
