# Generated by Django 4.1.6 on 2023-02-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_customerpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpayment',
            name='account_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='expiry',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
