# Generated by Django 4.1.6 on 2023-02-07 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0005_rename_desc_product_description'),
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(default=0, max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ManyToManyField(to='Catalogue.product')),
                ('shopping_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.shoppingsession')),
            ],
        ),
    ]
