# Generated by Django 4.1.6 on 2023-02-07 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='products',
        ),
    ]
