# Generated by Django 4.1.6 on 2023-02-11 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0007_order_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='shoppingsession',
            options={'ordering': ('-created_at',)},
        ),
    ]
