# Generated by Django 4.1.6 on 2023-02-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0008_alter_cart_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingsession',
            name='order_placed',
            field=models.BooleanField(default=False),
        ),
    ]
