# Generated by Django 4.1.6 on 2023-02-07 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('desc', models.TextField(blank=True)),
                ('discount_percent', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('desc', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, max_length=250)),
                ('size', models.CharField(blank=True, max_length=5)),
                ('SKU', models.CharField(db_index=True, max_length=250, unique=True)),
                ('price', models.CharField(default=0, max_length=250)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogue.productcategory')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogue.discount')),
            ],
        ),
    ]
