# Generated by Django 4.1.6 on 2023-02-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0002_discount_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_percent',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
