# Generated by Django 4.1.6 on 2023-02-07 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0004_rename_desc_discount_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desc',
            new_name='description',
        ),
    ]
