# Generated by Django 4.1.6 on 2023-02-11 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0002_alter_productreview_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ('-created_at',)},
        ),
    ]
