name: APO-Backend Tests
env:
  SECRET_KEY: 'django-insecure-!drlp9)c*blaz--aul7k^bn9ryxjl$7sjm+sr@=dt-k(3cnd$1'
  DEBUG: False
  DB_TYPE: 'postgresql'
  DB_NAME: 'testingdb'
  DB_USER: 'testinguser'
  DB_PASSWORD: 'testingpassword'
  ALLOWED_HOSTS: '*'

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: |
        cd APO-Backend 
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Django Testing
      run: |
        cd APO-Backend
        python3 manage.py test
